### ISSUE TITLE
혹시 푸시알림 끄고키는거 가능하나요

### ISSUE THREAD

**Issue by hwahyang1** [anaclumos/youtube-comment-language-filter#14]
메인컴에서 업데이트 알림 뜨는건 상관이 없는데 서브컴에서도 업데이트 알림이 날아오니까 끄고싶은데 혹시 설정 만들어 주실 수 있나요?

**Comment by anaclumos** [comment]
안녕하세요!
v1.3.2에서 알림을 해제할 수 있는 옵션을 추가하였으며 크롬 익스텐션 스토어와 파이어폭스 애드온 스토어에 제출하였습니다. 아마 내일쯤 업데이트될 것으로 예상합니다.
프로젝트에 관심을 가져주셔서 정말 감사합니다.
